version: 2
jobs:
  test:
    docker:
      - image: docker-local-artifacts.transferwise.com/circle_oracle_jvm8:171
        user: circleci
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew --no-daemon --stacktrace --console=plain clean check
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
  publish_snapshot:
    docker:
      - image: docker-local-artifacts.transferwise.com/circle_oracle_jvm8:171
        user: circleci
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Publish snapshot
          command: ./gradlew --no-daemon --stacktrace --console=plain publish
  release:
    docker:
      - image: docker-local-artifacts.transferwise.com/circle_oracle_jvm8:171
        user: circleci
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - add_ssh_keys:
          fingerprints:
            - "3d:19:d8:2b:6b:28:47:d9:1c:71:72:ee:be:48:c9:36"
      - run:
          name: Set git config
          command: git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee
      - run:
          name: Publish release
          command: ./gradlew --no-daemon --stacktrace --console=plain release publish -Prelease.useAutomaticVersion=true

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - publish_snapshot:
          context: artifactory-deploy
          requires:
            - test
  release_and_update_version:
    jobs:
      - release:
          context: artifactory-deploy
          filters:
            branches:
              only: master