version: 2
jobs:
  test:
    docker:
      - image: arti.tw.ee/circle_oracle_jvm8:8u181
    resource_class: small
    environment:
      TERM: vt100
    steps:
      - checkout
      - restore_cache:
          # here we restore the .gradle folder, so we don't have to download all the jars again.
          # the cache key is the checksum of build.gradle, so a new version of the cache will
          # be produced if you changed something in the build script (likely you changed a dependency)
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew clean check --no-daemon --stacktrace --console=plain
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/test-results/
      - save_cache:
          # here we save the .gradle folder, so we can reuse it in the later steps and also later builds.
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
  publish_snapshot:
    docker:
      - image: arti.tw.ee/circle_oracle_jvm8:8u181
    resource_class: small
    environment:
      TERM: vt100
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Publish snapshot
          command: ./gradlew publish --no-daemon --stacktrace --console=plain
  release:
    docker:
    - image: arti.tw.ee/circle_oracle_jvm8:8u181
    resource_class: small
    environment:
      TERM: vt100
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - add_ssh_keys:
          fingerprints:
            - "3d:19:d8:2b:6b:28:47:d9:1c:71:72:ee:be:48:c9:36"
      - run:
          # this step is required for pushing to git, otherwise git push in the release plugin will fail
          name: Set git config
          command: git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee
      - run:
          name: Publish release
          command: ./gradlew release --no-daemon --stacktrace -Prelease.useAutomaticVersion=true --console=plain
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - release:
          context: artifactory-deploy
          requires:
            - test
          filters:
            branches:
              only: master
      - publish_snapshot:
          context: artifactory-deploy
          requires:
            - test
          filters:
            branches:
              ignore: master